platform :ios, '9.0'
use_frameworks!

target 'ALSLayouts Example' do
  pod 'ALSLayouts', :path => '../'
  pod 'UITableView+FDTemplateLayoutCell', '~> 1.5.beta'
  
  target 'ALSLayouts Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 0.8'
  pod 'Nimble', '~> 3.0'
  pod 'FBSnapshotTestCase'
  pod 'Nimble-Snapshots'
  end
end
